services:
    docker:
        command: '--storage-driver overlay2'
        image: 'docker:dind'
        ports:
            - '2376:2376'
        volumes:
            - '/home/prabhat/Documents/CICDHome/Jenkins/prod/jenkins-data:/var/jenkins_home'
            - '/home/prabhat/Documents/CICDHome/Jenkins/prod/jenkins-docker-certs:/certs/client'
        environment:
            - DOCKER_TLS_CERTDIR=/certs
        networks:
            jenkins:
                aliases:
                    - docker
        privileged: true
        container_name: jenkins-docker
    myjenkins-blueocean:
        build: .
        volumes:
            - '/home/prabhat/Documents/CICDHome/Jenkins/prod/jenkins-docker-certs:/certs/client:ro'
            - '/home/prabhat/Documents/CICDHome/Jenkins/prod/jenkins-data:/var/jenkins_home'
        ports:
            - '50000:50000'
            - '8080:8080'
        environment:
            - DOCKER_TLS_VERIFY=1
            - DOCKER_CERT_PATH=/certs/client
            - 'DOCKER_HOST=tcp://docker:2376'
        networks:
            jenkins:
                aliases:
                    - jenkins.sriauronet.lan
                    - jenkins
        restart: on-failure
        container_name: jenkins-blueocean
networks:
    jenkins: {}



