version: "3.8"
services:
  jenkins_controller_uat:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    container_name: jenkins_controller_uat
    ports:
      - 8081:8080
      - 50000:50000
    volumes:
      - /home/prabhat/Documents/CICDHome/Jenkins/uat_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins_net_uat
networks:
  jenkins_net_uat:
    driver: bridge