version: "2"
services:
  jenkins_uat:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    container_name: jenkins_uat
    volumes:
      - jenkins_home:/var/jenkins_home
  ssh-agent_uat:
    image: jenkins/ssh-agent

volumes:
  jenkins_home:
        type: bind
        source: /home/prabhat/Documents/CICDHome/Jenkins/prod

