version: "2"
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    container_name: jenkins_uat
    volumes:
      - /home/prabhat/Documents/CodingHome/jenkins/uat:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
  ssh-agent:
    image: jenkins/ssh-agent
